<?php

/*
	User Profile page for Mirau's Modular Website Platform
	User is sent here from a URL generated by the bot.
*/
require 'lib/header.php';
require "lib/mysql.php";

$sql = "SELECT * FROM user WHERE id='".$_GET['user']."'";
$result = $mysqli->query($sql);
if(mysqli_num_rows($result) > 0){
	foreach($result as $row){
		$user = $row;
	}
} else {
	header("Location: index.php");
}

if(isset($user)){
	echo "<img src=\"".$user['avatar']."\" class=\"img-fluid rounded-circle\">";
	echo "Hey it's the profile for ".$user['name']."!";

	
}

require 'lib/footer.php';
?>