<?php

/*
	Registration page for Mirau's Modular Website Platform
	User is sent here from a URL generated by the bot.
*/
require 'lib/header.php';
$check = TRUE;

if(isset($_SESSION['logged']) && $_SESSION['logged'] === TRUE){
	echo "<div class=\"alert alert-warning alert-dismissible fade show\">You can not register a new account while already logged into another account. Please logout of this account and try again.</div>";
	$check = FALSE;
} elseif (!isset($_GET['usr'])) {
	if(!isset($_POST['pwd'])){
		header("Location: index.php");
		$check = FALSE;
	}
} else {
	require "lib/mysql.php";
	$sql = "SELECT * FROM user WHERE name='".$_GET['usr']."'";
	$result = $mysqli->query($sql);
	if(mysqli_num_rows($result) > 0){
		foreach($result as $row){
			if($row['reg_date'] != '0000-00-00'){
				$check = FALSE;
				echo "<div class=\"alert alert-warning alert-dismissible fade show\">An account with this username already exists.</div>";
			}
		}
	} else {
		$check = FALSE;
		echo "<div class=\"alert alert-warning alert-dismissible fade show\">New accounts need to begin registration with Rumia-bot on Discord!</div>";
	}
}


if($check === TRUE) {
	echo "
	<div class=\"jumbotron\">";
		if(!isset($_POST['page'])){
			echo "
			<h2>Registration for ".$_GET['usr']."</h2>
			<p>
			<form action=\"#\" method=post>
			<input type=\"hidden\" id=\"usr\" name=\"usr\" value=".$_GET['usr'].">
			<input type=\"hidden\" id=\"page\" name=\"page\" value=2>
			<input type=\"password\" class=\"form-control\" id=\"pw1\" name=\"pw1\" placeholder=\"Enter New Password\" required>
			
			<button type=\"submit\" class=\"btn btn-success btn-lg \" >- Next -</button>
			</form>
			</p>";
		}
		if(isset($_POST['page']) && $_POST['page'] == 2){
			echo "
			<h2>Registration for ".$_POST['usr']."</h2>
			<p>
			<form action=\"#\" method=post>
			<input type=\"hidden\" id=\"usr\" name=\"usr\" value=".$_POST['usr'].">
			<input type=\"hidden\" id=\"pw1\" name=\"pw1\" value=".$_POST['pw1'].">
			<input type=\"hidden\" id=\"page\" name=\"page\" value=3>
			<input type=\"password\" class=\"form-control\" id=\"pw2\" name=\"pw2\" placeholder=\"Confirm New Password\" required>
			<button type=\"submit\" class=\"btn btn-success btn-lg \" >- Next -</button>
			</form>
			</p>";
		}
		if(isset($_POST['page']) && $_POST['page'] == 3){
			echo "
			<h2>Registration for ".$_POST['usr']."</h2>
			<p>";
			if($_POST['pw1'] === $_POST['pw2']){
				$sql = "UPDATE user SET secret='".hash('sha256', $_POST['pw1'])."', ip='".$_SERVER['REMOTE_ADDR']."', power=1, reg_date='".date("Y-m-d")."'  WHERE name='".$_POST['usr']."'";
				$result = $mysqli->query($sql);
			//UPDATE USR ROW TO ACTIVATE THE ACCOUNT INCLUDING CURRENT TIME, POWER, AND HASHED PWD
				echo "Account successfully created. Only one last step to activate your account!";
				echo "<form action=\"index.php\" method=post>
				<button type=\"submit\" class=\"btn btn-success btn-lg \" >- Activate -</button>
				</form>";
			} else {
				echo "The passwords you entered do not match.";
				echo "<form action=\"register.php\" method=get>
					<input type=\"hidden\" id=\"usr\" name=\"usr\" value=".$_POST['usr'].">
					<button type=\"submit\" class=\"btn btn-success btn-lg \" >- Start Over -</button>
					</form>";
			}
			
			
			echo "</p>";
		}
		
	echo "</div>";
}



require 'lib/footer.php';
?>